/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.gui.view;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Andres Garcia
 */
public class Schweitze extends javax.swing.JFrame {

    /**
     * Creates new form frmSchweitzer
     */
    public Schweitze() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuFile = new javax.swing.JMenu();
        jMnuItemExit = new javax.swing.JMenuItem();
        jMenuItemAbout = new javax.swing.JMenuItem();
        jMnuClient = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemGenerate = new javax.swing.JMenuItem();
        jMenuVerifyOrder = new javax.swing.JMenu();
        jMenuItemVerify = new javax.swing.JMenuItem();
        jMenuItemCancel = new javax.swing.JMenuItem();
        jMnuTechnician = new javax.swing.JMenu();
        jMnuItemVerify = new javax.swing.JMenu();
        jMenuItemVerifyData = new javax.swing.JMenuItem();
        jMenuItemUpdateData = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schweitzer");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jMnuFile.setText("Schweitzer");

        jMnuItemExit.setText("Salir");
        jMnuFile.add(jMnuItemExit);

        jMenuItemAbout.setText("Acerca de");
        jMnuFile.add(jMenuItemAbout);

        jMenuBar1.add(jMnuFile);

        jMnuClient.setText("Cliente");

        jMenu1.setText("Servicios");

        jMenuItemGenerate.setText("Generar Orden");
        jMenuItemGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemGenerateActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemGenerate);

        jMenuVerifyOrder.setText("Editar Orden");

        jMenuItemVerify.setText("Verificar estado de orden");
        jMenuVerifyOrder.add(jMenuItemVerify);

        jMenuItemCancel.setText("Cancelar orden");
        jMenuVerifyOrder.add(jMenuItemCancel);

        jMenu1.add(jMenuVerifyOrder);

        jMnuClient.add(jMenu1);

        jMenuBar1.add(jMnuClient);

        jMnuTechnician.setText("Tecnico");

        jMnuItemVerify.setText("Verificar Trabajos Pendientes");

        jMenuItemVerifyData.setText("Verificar info de trabajo");
        jMnuItemVerify.add(jMenuItemVerifyData);

        jMenuItemUpdateData.setText("Actualizar estado de trabajo");
        jMnuItemVerify.add(jMenuItemUpdateData);

        jMnuTechnician.add(jMnuItemVerify);

        jMenuBar1.add(jMnuTechnician);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 309, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemGenerateActionPerformed
        GenerateOrder generateOrder = new GenerateOrder();
        generateOrder.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItemGenerateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Schweitze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Schweitze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Schweitze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Schweitze.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Schweitze().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemCancel;
    private javax.swing.JMenuItem jMenuItemGenerate;
    private javax.swing.JMenuItem jMenuItemUpdateData;
    private javax.swing.JMenuItem jMenuItemVerify;
    private javax.swing.JMenuItem jMenuItemVerifyData;
    private javax.swing.JMenu jMenuVerifyOrder;
    private javax.swing.JMenu jMnuClient;
    private javax.swing.JMenu jMnuFile;
    private javax.swing.JMenuItem jMnuItemExit;
    private javax.swing.JMenu jMnuItemVerify;
    private javax.swing.JMenu jMnuTechnician;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo.png")));
    }
}
